from _typeshed import Incomplete
from lumopt.utilities.load_lumerical_scripts import load_from_lsf as load_from_lsf

class BaseScript:
    callable_obj: Incomplete
    project_file: Incomplete
    script_str: Incomplete
    def __init__(self, script_obj) -> None: ...
    def __call__(self, cad_handle): ...
    def eval(self, cad_handle): ...
    def __eq__(self, other): ...
