from _typeshed import Incomplete

class GradientFields:
    forward_fields: Incomplete
    adjoint_fields: Incomplete
    def __init__(self, forward_fields, adjoint_fields) -> None: ...
    def sparse_perturbation_field(self, x, y, z, wl, real: bool = True): ...
    def get_field_product_E_forward_adjoint(self): ...
    def get_forward_dot_adjoint_center(self): ...
    def plot(self, fig, ax_forward, ax_gradients, original_grid: bool = True) -> None: ...
    def plot_gradients(self, fig, ax_gradients, original_grid) -> None: ...
    def plot_eps(self, ax_eps) -> None: ...
    def boundary_perturbation_integrand(self): ...
    @staticmethod
    def spatial_gradient_integral_on_cad(sim, forward_fields, adjoint_fields, wl_scaling_factor): ...
