from _typeshed import Incomplete
from matplotlib.animation import FileMovieWriter

class SnapShots(FileMovieWriter):
    supported_formats: Incomplete
    def __init__(self, *args, extra_args: Incomplete | None = None, **kwargs) -> None: ...
    fname_format_str: str
    def setup(self, fig, dpi, frame_prefix) -> None: ...
    def grab_frame(self, **fig_kwargs) -> None: ...
    def finish(self) -> None: ...

class Plotter:
    plot_history: Incomplete
    plot_fields: Incomplete
    ax: Incomplete
    movie: Incomplete
    writer: Incomplete
    def __init__(self, movie: bool = True, plot_history: bool = True, plot_fields: bool = True) -> None: ...
    def clear(self) -> None: ...
    def update_fom(self, optimization) -> None: ...
    def update_gradient(self, optimization) -> None: ...
    def update_geometry(self, optimization) -> None: ...
    def draw_and_save(self) -> None: ...
    def set_legend(self, legend) -> None: ...
