from _typeshed import Incomplete

class Wavelengths:
    custom: Incomplete
    wavelength_points: Incomplete
    start: Incomplete
    points: Incomplete
    stop: Incomplete
    def __init__(self, start, stop: Incomplete | None = None, points: int = 1) -> None: ...
    def min(self): ...
    def max(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, item): ...
    def asarray(self): ...
