[doc]
name = "integrated-photonics"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "index"
index = "index.tex"
type = "pdf"

[[output]]
name = "task2"
index = "task2.tex"
type = "pdf"

[[output]]
name = "task3"
index = "task3.tex"
type = "pdf"
