from lumopt.utilities.fields import Fields as Fields, FieldsNoInterp as FieldsNoInterp

def get_lambda_from_cad(fdtd, field_result_name): ...
def get_fields_on_cad(fdtd, monitor_name, field_result_name, get_eps, get_D, get_H, nointerpolation, unfold_symmetry: bool = True) -> None: ...
def scale_fields_on_cad(fdtd, field_name, scaling_factors) -> None: ...
def get_fields(fdtd, monitor_name, field_result_name, get_eps, get_D, get_H, nointerpolation, unfold_symmetry: bool = True, on_cad_only: bool = False): ...
def set_spatial_interp(fdtd, monitor_name, setting) -> None: ...
def get_eps_from_sim(fdtd, monitor_name: str = 'opt_fields', unfold_symmetry: bool = True): ...
