from _typeshed import Incomplete
from lumopt.utilities.wavelengths import Wavelengths as Wavelengths

class IntensityVolume:
    monitor_name: Incomplete
    target_fom: float
    multi_freq_src: bool
    def __init__(self, field_region_name) -> None: ...
    def initialize(self, sim) -> None: ...
    def make_forward_sim(self, sim) -> None: ...
    def make_adjoint_sim(self, sim) -> None: ...
    def can_make_adjoint_sim(self, sim): ...
    def check_monitor(self, sim) -> None: ...
    wavelengths: Incomplete
    T_fwd_vs_wavelength: Incomplete
    def get_fom(self, sim): ...
    @staticmethod
    def fr_monitor_fom(sim, field_region_name): ...
    def get_adjoint_field_scaling(self, sim): ...
    @staticmethod
    def get_wavelengths(sim): ...
    def fom_gradient_wavelength_integral_on_cad(self, sim, grad_var_name, wl): ...
    def fom_gradient_wavelength_integral(self, T_fwd_partial_derivs_vs_wl, wl): ...
