from _typeshed import Incomplete
from lumopt.optimizers.maximizer import Maximizer as Maximizer

class FixedStepGradientDescent(Maximizer):
    max_dx: Incomplete
    all_params_equal: Incomplete
    noise_magnitude: Incomplete
    predictedchange_hist: Incomplete
    def __init__(self, max_dx, max_iter, all_params_equal, noise_magnitude, scaling_factor) -> None: ...
    current_params: Incomplete
    current_fom: Incomplete
    def run(self): ...
    def calculate_change(self, gradients, dx): ...
    def add_noise(self) -> None: ...
    def enforce_bounds(self, params): ...
